backend:
  - backend/**/*
  - changed-files:
      - any-glob-to-any-file: ['backend/**/*']

frontend:
  - frontend/**/*
  - changed-files:
      - any-glob-to-any-file: ['frontend/**/*']

mobile:
  - mobile/**/*
  - changed-files:
      - any-glob-to-any-file: ['mobile/**/*']

documentation:
  - docs/**/*
  - '*.md'
  - changed-files:
      - any-glob-to-any-file: ['docs/**/*', '*.md']

uk-compliance:
  - changed-files:
      - any-glob-to-any-file: 
        - '**/ukVAT.ts'
        - '**/documentGenerator.ts'
        - '**/compliance/**/*'
        - '**/bs5839/**/*'

security:
  - changed-files:
      - any-glob-to-any-file: 
        - '**/auth/**/*'
        - '**/middleware/**/*'
        - '**/security/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file: 
        - '**/package.json'
        - '**/package-lock.json'
        - '**/yarn.lock'
        - '**/Dockerfile'
